---
- name: Backup NFS share using restic
  hosts: openmediavault
  gather_facts: true
  become: true
  environment:
    RESTIC_PASSWORD_COMMAND: "{{ restic_password_command }}"
    RESTIC_REPOSITORY: "{{ restic_repository }}"
  tasks:
    - name: Install restic
      ansible.builtin.apt:
        name: restic
        update_cache: true

    - name: Init repository
      ansible.builtin.shell: |
        restic init
      register: init_result
      changed_when: init_result.rc == 0
      ignore_errors: true

    - name: Create backup
      ansible.builtin.shell: |
        restic backup --limit-upload 1024 {{ nfs_share_path }}
      register: backup_result
      changed_when: backup_result.rc == 0

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ backup_result.stdout_lines }}"
