---
- name: Restore latest NFS share backup to localhost using restic
  hosts: localhost
  gather_facts: true
  environment:
    RESTIC_PASSWORD_COMMAND: "{{ restic_password_command }}"
    RESTIC_REPOSITORY: "{{ restic_repository }}"
  tasks:
    - name: List snapshots
      ansible.builtin.shell: |
        restic snapshots
      register: snapshots_result
      changed_when: false

    - name: Debug
      ansible.builtin.debug:
        msg: "{{ snapshots_result.stdout_lines }}"

    - name: Prompt snapshot ID
      ansible.builtin.pause:
        prompt: "Enter snapshot ID to restore"
      register: snapshot_id

    - name: Create restore directory
      ansible.builtin.file:
        path: "/tmp/snapshot_{{ snapshot_id.user_input }}"
        mode: "0755"
        state: directory

    - name: Restore backup
      ansible.builtin.shell: |
        restic restore {{ snapshot_id.user_input }} --target /tmp/snapshot_{{ snapshot_id.user_input }}
      register: restore_result
      changed_when: restore_result.rc == 0
