---
- name: Restore latest NFS share backup to localhost using borgbackup
  hosts: localhost
  gather_facts: true
  environment:
    BORG_PASSPHRASE: "{{ borg_passphrase }}"
  tasks:
    - name: Find latest backup archive
      ansible.builtin.shell: |
        set -o pipefail && borg list {{ borg_repository }} | tail -n 1
      args:
        executable: /bin/bash
      register: latest_archive
      changed_when: false

    - name: Debug
      ansible.builtin.debug:
        var: latest_archive

    - name: Create restore directory
      ansible.builtin.file:
        path: "/tmp/backup_{{ latest_archive.stdout.split(' ')[0] }}"
        mode: "0755"
        state: directory

    - name: Extract latest backup
      ansible.builtin.shell: |
        borg extract {{ borg_repository }}::{{
          latest_archive.stdout.split(' ')[0]
        }} {{ nfs_share_path }}
      args:
        chdir: "/tmp/backup_{{ latest_archive.stdout.split(' ')[0] }}"
      register: restore_result
      changed_when: restore_result.rc == 0
