---
- name: Preare environment
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prepare_k3s

- name: Setup control
  hosts: control
  become: true
  roles:
    - role: k3s_control
    - role: helm
    - role: argocd_cli

- name: Setup worker
  hosts: worker
  become: true
  roles:
    - role: k3s_worker

- name: Configure cluster
  hosts: control
  roles:
    - role: certificate
    - role: sealed_secrets
    - role: argocd
