---
- name: Update system
  hosts: all
  gather_facts: true
  become: true
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        upgrade: true
        update_cache: true
        cache_valid_time: 600
